version: '3.5'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-python
    command: uwsgi --ini uwsgi.ini
    volumes:
      - ../creds.json:/catalog/creds.json
      - ../firebaseConfig.js:/catalog/static/js/firebaseConfig.js
      - .:/catalog

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
    depends_on:
      - web
