version: '3.5'

services:
  web:
    build: .
    command: uwsgi --ini uwsgi.ini
    expose:
      - "80"
    volumes:
      - ../creds.json:/catalog/creds.json
      - ../firebaseConfig.js:/catalog/static/js/firebaseConfig.js
      - .:/catalog

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web
