version: '3.5'

services:
  web:
    build: .
    command: python3 application.py
    ports:
      - "5000:5000"
    volumes:
      - ../creds.json:/catalog/creds.json
      - ../firebaseConfig.js:/catalog/static/js/firebaseConfig.js
      - .:/catalog
